/*
 * This source file was generated by the Gradle 'init' task
 */
package calculadora.ejercicio;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.InputMismatchException;
import java.util.Scanner;

import javax.swing.JFrame;
import javax.swing.JLabel;

import calculadora.ejercicio.domains.Dividir;
import calculadora.ejercicio.domains.LectorArchivo;
import calculadora.ejercicio.domains.Multiplicar;
import calculadora.ejercicio.domains.Operacion;
import calculadora.ejercicio.domains.Potencia;
import calculadora.ejercicio.domains.Restar;
import calculadora.ejercicio.domains.Sumar;

public class App {

    public static void main(String[] args) {

        String rutaArchivo = "app\\src\\main\\java\\calculadora\\ejercicio\\n"
                + //
                "umero.txt";

        try (Scanner scanner = new Scanner(System.in)) {
            System.out.println("Introduce el primer numero: ");
            double numero1 = scanner.nextDouble();

            System.out.println("Introduce el segundo numero: ");
            double numero2 = scanner.nextDouble();

            System.out.println("Seleccione la operacion que desea realizar: 1.Sumar, 2.Restar, 3.Multiplicar, 4.Dividir, 5.Potencia");
            int opcionSeleccionada = scanner.nextInt();

            Operacion operacion = null;

            switch (opcionSeleccionada) {
                case 1 ->
                    operacion = new Sumar(numero1, numero2);
                case 2 ->
                    operacion = new Restar(numero1, numero2);
                case 3 ->
                    operacion = new Multiplicar(numero1, numero2);
                case 4 ->
                    operacion = new Dividir(numero1, numero2);
                case 5 ->
                    operacion = new Potencia(numero1, numero2);
                default ->
                    throw new IllegalArgumentException("Opción no válida");
            }

            if (operacion != null) {
                System.out.println("El resultado es: " + operacion.calcular());
            }

            System.out.println("Por ultimo, deseas saber el numero que tiene el archivo? 1.Si, 2.No");
            int leerArchivo = scanner.nextInt();

            if (leerArchivo == 1) {
                try {
                    String contenidoDesdeArchivo = LectorArchivo.leerContenidoDelArchivo(rutaArchivo);
                    System.out.println("el contenido del archivo es " + contenidoDesdeArchivo);
                    // JOptionPane.showMessageDialog(null, "Contenido del archivo:\n" + contenidoDesdeArchivo);

                    //Tuve que usar JFrame y JLabel ya que tuve problemas al intentar usar JOptionPane
                    JFrame frame = new JFrame();
                    JLabel label = new JLabel("Contenido del archivo:\n" + contenidoDesdeArchivo);
                    frame.add(label);
                    frame.setSize(300, 200);
                    frame.setVisible(true);
                    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                } catch (FileNotFoundException e) {
                    System.out.println("Error: El archivo no fue encontrado: " + e.getMessage());
                } catch (IllegalArgumentException e) {
                    System.out.println("Error: " + e.getMessage());
                } catch (IOException e) {
                    System.out.println("Error al intentar leer el archivo: " + e.getMessage());
                }
            }

            System.out.println("Hasta luego!");

        } catch (ArithmeticException | IllegalArgumentException e) {
            System.out.println("Error: " + e.getMessage());
        } catch (InputMismatchException e) {
            System.out.println("Error: Debes ingresar un número válido.");
        }

    }
}
